Correct typespecs
elixir-sqlite/exqlite pull request #177
Opened 2021-12-02 14:01 UTC by reachfh

This corrects the typespecs, making it work with Dialyzer.

You can add Dialyzer to the project itself in `dev` and `test` environments (but not `prod`) by adding this to `deps()`:

    {:dialyxir, "~> 1.0", only: [:dev, :test], runtime: false}

then run

    mix dialyzer

2021-12-02 14:43 UTC, warmwaffles commented on lib/exqlite/sqlite3.ex
> +        # {:error, "Database busy"}
You can delete this commented line

2021-12-02 14:44 UTC, warmwaffles requested changes
Looks good, just need two questions addressed

2021-12-08 10:12 UTC, reachfh commented on lib/exqlite/sqlite3.ex
> +        # {:error, "Database busy"}
Ok

2021-12-08 10:12 UTC, reachfh commented on lib/exqlite/sqlite3.ex
> +      # _ -> {:error, "unhandled error"}
The only possible returns from execute are covered.

2021-12-08 10:13 UTC, reachfh commented
Updated branch

2021-12-08 14:12 UTC, warmwaffles approved these changes

2021-12-08 14:12 UTC, merged